//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoslynAnalizer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoslynAnalizer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type names should be all uppercase..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; contains lowercase letters.
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControllerMustBeAuthorizeDescription.
        /// </summary>
        internal static string ControllerMustBeAuthorizeDescription {
            get {
                return ResourceManager.GetString("ControllerMustBeAuthorizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControllerMustBeAuthorizeMessageFormat.
        /// </summary>
        internal static string ControllerMustBeAuthorizeMessageFormat {
            get {
                return ResourceManager.GetString("ControllerMustBeAuthorizeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControllerMustBeAuthorizeTitle.
        /// </summary>
        internal static string ControllerMustBeAuthorizeTitle {
            get {
                return ResourceManager.GetString("ControllerMustBeAuthorizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntitiesMastBeDataContractDescription.
        /// </summary>
        internal static string EntitiesMastBeDataContractDescription {
            get {
                return ResourceManager.GetString("EntitiesMastBeDataContractDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntitiesMastBeDataContractMessageFormat.
        /// </summary>
        internal static string EntitiesMastBeDataContractMessageFormat {
            get {
                return ResourceManager.GetString("EntitiesMastBeDataContractMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntitiesMastBeDataContractTitle.
        /// </summary>
        internal static string EntitiesMastBeDataContractTitle {
            get {
                return ResourceManager.GetString("EntitiesMastBeDataContractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntitiesMastBePublicDescription.
        /// </summary>
        internal static string EntitiesMastBePublicDescription {
            get {
                return ResourceManager.GetString("EntitiesMastBePublicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntitiesMastBePublicMessageFormat.
        /// </summary>
        internal static string EntitiesMastBePublicMessageFormat {
            get {
                return ResourceManager.GetString("EntitiesMastBePublicMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntitiesMastBePublicTitle.
        /// </summary>
        internal static string EntitiesMastBePublicTitle {
            get {
                return ResourceManager.GetString("EntitiesMastBePublicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntitiesMastHaveIdDescription.
        /// </summary>
        internal static string EntitiesMastHaveIdDescription {
            get {
                return ResourceManager.GetString("EntitiesMastHaveIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntitiesMastHaveIdMessageFormat.
        /// </summary>
        internal static string EntitiesMastHaveIdMessageFormat {
            get {
                return ResourceManager.GetString("EntitiesMastHaveIdMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntitiesMastHaveIdTitle.
        /// </summary>
        internal static string EntitiesMastHaveIdTitle {
            get {
                return ResourceManager.GetString("EntitiesMastHaveIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntitiesMastHaveNameDescription.
        /// </summary>
        internal static string EntitiesMastHaveNameDescription {
            get {
                return ResourceManager.GetString("EntitiesMastHaveNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntitiesMastHaveNameMessageFormat.
        /// </summary>
        internal static string EntitiesMastHaveNameMessageFormat {
            get {
                return ResourceManager.GetString("EntitiesMastHaveNameMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntitiesMastHaveNameTitle.
        /// </summary>
        internal static string EntitiesMastHaveNameTitle {
            get {
                return ResourceManager.GetString("EntitiesMastHaveNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InheritanceControllerDescription.
        /// </summary>
        internal static string InheritanceControllerDescription {
            get {
                return ResourceManager.GetString("InheritanceControllerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InheritanceControllerMessageFormat.
        /// </summary>
        internal static string InheritanceControllerMessageFormat {
            get {
                return ResourceManager.GetString("InheritanceControllerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InheritanceControllerTitle.
        /// </summary>
        internal static string InheritanceControllerTitle {
            get {
                return ResourceManager.GetString("InheritanceControllerTitle", resourceCulture);
            }
        }
    }
}
