// <auto-generated />
namespace NorthwindEF.Migration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class version_3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version_3));
        
        string IMigrationMetadata.Id
        {
            get { return "201704182132066_version_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
